name: Publish

on: workflow_dispatch

env:
  SOLUTION_FILE_PATH: ./akebi-gc.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Disable Custom Build Steps
      shell: bash
      run: |
        $GITHUB_WORKSPACE/CustomBuildStepsDisabler.exe
        
    - name: Build Akebi-GC solution
      working-directory: $GITHUB_WORKSPACE
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Upload Akebi-GC latest
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Akebi-GC
        path: $GITHUB_WORKSPACE/bin/Release/*
        if-no-files-found: error
