name: Publish

on: workflow_dispatch

env:
  SOLUTION_FILE_PATH: ./akebi-gc.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Clone Akebi-GC
      shell: bash
      run: |
        curl -o Custom.After.Microsoft.Common.targets https://gist.githubusercontent.com/sayedihashimi/6c352cb78591f7abe04f/raw/39ce45866fec3afd5c937262c65aa5d1855405a1/nopreorpostevents.targets
        git clone --recurse-submodules https://github.com/Akebi-Group/Akebi-GC
        cd Akebi-GC
        ls ./

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ./Akebi-GC
      env:
        CustomAfterMicrosoftCommonTargets: ./Custom.After.Microsoft.Common.targets
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Publish Akebi-GC latest
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Akebi-GC
        path: ./Akebi-GC/bin/Release/*
        if-no-files-found: error
